// Package conust transforms numbers into string tokens for which the simple string comparison
// produces the same result as the numeric comparison of the original numbers would.
// The input is not limited to decimal numbers, other bases up to base 36 are accepted with the
// restriction that it must be lowercased.
// The expected input format is ^[+-]?[0-9a-z]+(\.[0-9a-z]+)?$ Failing to satisfy this results in encoding failures.
//
// Transforming tokens back into numbers is also possible. This operation requires that the
// tokens are as they were generated by the encoder, modifications to them might cause decoding failures.
//
// The conversion adds a few characters to the length of the original numeric string, but at
// the same time it can save some space by storing only the significant portion of the number
// omitting trailing and leading zeros of it in the output.
//
// Beside transforming single numbers to sortable strings, you can also transform a string containing both
// text and numbers into a properly sortable version. However, the reverse transformation of such mixed strings
// is not possible.
package conust

// [48 49 50 51 52 53 54 55 56 57
// 97 98 99 100 101 102 103 104 105 106
// 107 108 109 110 111 112 113 114 115 116
// 117 118 119 120 121 122]
var digits36 = [...]byte{
	'0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
	'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j',
	'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
	'u', 'v', 'w', 'x', 'y', 'z'}

var uppercaseDigits36 = [...]byte{
	'0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
	'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J',
	'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T',
	'U', 'V', 'W', 'X', 'Y', 'Z'}

var digits36Reversed = [...]byte{
	'z', 'y', 'x', 'w', 'v', 'u', 't', 's', 'r', 'q',
	'p', 'o', 'n', 'm', 'l', 'k', 'j', 'i', 'h', 'g',
	'f', 'e', 'd', 'c', 'b', 'a', '9', '8', '7', '6',
	'5', '4', '3', '2', '1', '0'}

const maxDigitValue = 35
const maxMagnitudeDigitValue = 34

const digit0 byte = '0'            // ASCII 48
const digit9 byte = '9'            // ASCII 57
const digitUppercaseA byte = 'A'   // ASCII 65
const digitUppercaseZ byte = 'Z'   // ASCII 90
const digitA byte = 'a'            // ASCII 97
const digitZ byte = 'z'            // ASCII 122
const digitNormalizerBit byte = 32 // 0-9, a-z all have this bit, A-Z do not
const minusByte byte = '-'
const plusByte byte = '+'
const minPrintableAsciiByte = 32       // space
const maxPrintableAsciiByte byte = 126 // ~
const placeholderInvalidSeparator byte = 0

const signNegativeMagPositive byte = '3'
const signNegativeMagNegative byte = '4'
const zeroOutput = "5"
const signPositiveMagNegative byte = '6'
const signPositiveMagPositive byte = '7'

// LessThanAny is a string which is less than any encoded value
// You can use this constant as the exclusive lower boundary for generated tokens.
const LessThanAny = "2"

// GreaterThanAny is a string which is greater than any encoded value.
// You can use this constant as the exclusive upper boundary for generated tokens.
const GreaterThanAny = "8"

const zeroInput = "0"

const negativeNumberTerminator byte = '~'
const positiveNumberTerminator byte = ' '

func isMinusByte(b byte) bool {
	return b == minusByte
}

func isPlusByte(b byte) bool {
	return b == plusByte
}

func isSignByte(b byte) bool {
	return isMinusByte(b) || isPlusByte(b)
}

func isDigit(b byte) bool {
	return (b >= digit0 && b <= digit9) ||
		(b >= digitA && b <= digitZ) ||
		(b >= digitUppercaseA && b <= digitUppercaseZ)
}

func isAllowedAsSeparator(b byte) bool {
	return !isDigit(b) &&
		!isSignByte(b) &&
		b >= minPrintableAsciiByte &&
		b <= maxPrintableAsciiByte
}

func digitToInt(digit byte) int {
	if digit <= digit9 {
		return int(digit - digit0)
	}
	if digit <= digitUppercaseZ {
		return 10 + int(digit-digitUppercaseA)
	}
	return 10 + int(digit-digitA)
}

func reversedDigitToInt(digit byte) int {
	if digit <= digit9 {
		return 26 + int(digit9-digit)
	}
	if digit <= digitUppercaseZ {
		return int(digitUppercaseZ - digit)
	}
	return int(digitZ - digit)
}

func intToDigit(i int) byte {
	return digits36[i]
}

func intToReversedDigit(i int) byte {
	return digits36Reversed[i]
}

func reverseDigit(digit byte) byte {
	return intToReversedDigit(digitToInt(digit))
}

func normalizeDigit(digit byte) byte {
	return digit | digitNormalizerBit
}
